In [90]:
import pandas as pd
import numpy as np

In [91]:
original_model_data = pd.read_csv('~/git/downtownrecovery/shinyapp/input_data/all_model_features_1015_weather.csv')

updated_us_downtown_vars = pd.read_csv('~/data/downtownrecovery/us_downtown_data_20230721.csv')

updated_us_city_vars = pd.read_csv("~/data/downtownrecovery/curated_data/us_city_acs_vars_2019.csv")
# so that this is consistent with canadian definition - previously omitted wfh
updated_us_city_vars['pct_commute_others_city'] = 100 - updated_us_city_vars['pct_commute_auto_city'] - updated_us_city_vars['pct_commute_public_transit_city'] - updated_us_city_vars['pct_commute_bicycle_city'] - updated_us_city_vars['pct_commute_walk_city']
updated_can_vars =  pd.read_csv('~/data/downtownrecovery/curated_data/can_city_index_with_features_20230803.csv')

In [152]:
updated_us_downtown_vars[["city"] + updated_us_downtown_vars.columns[updated_us_downtown_vars.columns.str.contains("commute_time")].values.tolist()]

                city  average_commute_time_downtown
0           New York                      27.254815
1        Los Angeles                      32.424316
2            Chicago                      23.429021
3            Houston                      18.465414
4            Phoenix                      19.184081
5       Philadelphia                      25.873410
6        San Antonio                       0.000000
7          San Diego                      24.147055
8             Dallas                      22.375326
9           San Jose                      32.561224
10            Austin                      20.795858
11      Jacksonville                       0.000000
12        Fort Worth                      23.519264
13          Columbus                      19.412109
14      Indianapolis                      19.659319
15         Charlotte                      19.373118
16     San Francisco                      30.391523
17           Seattle                      23.069554
18            Denver                      25.402516
19     Washington DC                      22.185928
20         Nashville                       0.000000
21     Oklahoma City                       0.000000
22           El Paso                      31.020607
23            Boston                      22.766241
24          Portland                       0.000000
25         Las Vegas                      28.180595
26           Detroit                      19.618899
27           Memphis                      19.725969
28        Louisville                       0.000000
29         Baltimore                      30.223025
30         Milwaukee                      20.392892
31       Albuquerque                      18.961627
32            Tucson                      19.990454
33            Fresno                       0.000000
34        Sacramento                      22.048493
35       Kansas City                      19.529955
36           Atlanta                      19.833333
37             Omaha                      16.159348
38  Colorado Springs                      20.548135
39           Raleigh                      24.337668
40             Miami                      23.078683
41           Oakland                      33.629319
42       Minneapolis                      17.937453
43             Tulsa                       0.000000
44       Bakersfield                      17.391359
45           Wichita                       0.000000
46             Tampa                      22.247996
47       New Orleans                      16.441748
48         Cleveland                      19.554184
49          Honolulu                      21.824892
50        Cincinnati                      18.805942
51        Pittsburgh                      18.719340
52    Salt Lake City                      19.903407
53          St Louis                      20.075982
54           Orlando                      23.039271

In [92]:
updated_us_downtown_vars.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', '_c0', 'city', 'total_pop_downtown',
       'pct_singlefam_downtown', 'pct_multifam_downtown',
       'pct_mobile_home_and_others_downtown', 'pct_renter_downtown',
       'median_age_downtown', 'bachelor_plus_downtown',
       'median_hhinc_downtown', 'median_rent_downtown', 'pct_vacant_downtown',
       'pct_nhwhite_downtown', 'pct_nhblack_downtown', 'pct_nhasian_downtown',
       'pct_hisp_downtown', 'pct_commute_auto_downtown',
       'pct_commute_public_transit_downtown', 'pct_commute_bicycle_downtown',
       'pct_commute_walk_downtown', 'pct_commute_home_downtown',
       'pct_commute_others_downtown', 'housing_units_downtown',
       'average_commute_time_downtown', 'pct_others_downtown', 'total_jobs',
       'pct_jobs_agriculture_forestry_fishing_hunting',
       'pct_jobs_mining_quarrying_oil_gas', 'pct_jobs_utilities',
       'pct_jobs_construction', 'pct_jobs_manufacturing',
       'pct_jobs_wholesale_trade', 'pct_jobs_retail_trade',
       'pct_jobs_transport_warehouse', 'pct_jobs_information',
       'pct_jobs_finance_insurance', 'pct_jobs_real_estate',
       'pct_jobs_professional_science_techical',
       'pct_jobs_management_of_companies_enterprises',
       'pct_jobs_administrative_support_waste',
       'pct_jobs_educational_services',
       'pct_jobs_healthcare_social_assistance',
       'pct_jobs_arts_entertainment_recreation',
       'pct_jobs_accomodation_food_services', 'pct_jobs_other',
       'pct_jobs_public_administration', 'employment_entropy',
       'land_area_downtown_m2', 'land_area_downtown_km2',
       'population_density_downtown_m2', 'employment_density_downtown_m2',
       'housing_density_downtown_m2', 'population_density_downtown_km2',
       'employment_density_downtown_km2', 'housing_density_downtown_km2'],
      dtype='object')

In [111]:
updated_us_city_vars[updated_us_city_vars.columns[updated_us_city_vars.columns.str.contains("density")].values.tolist()]

,housing_density_city,population_density_city,population_density_city_km2,housing_density_city_km2
0,0.000463,0.001218,1217.972794,463.339475
1,0.000388,0.000878,878.382587,388.167167
2,0.000321,0.000974,974.336562,320.926200
3,0.000602,0.001767,1766.904164,601.849943
4,0.001229,0.003266,3266.066504,1229.308974
5,0.001197,0.002936,2936.497270,1197.126719
6,0.000777,0.001979,1979.026202,776.913862
7,0.000647,0.001670,1670.073594,647.415908
8,0.003275,0.007203,7202.644521,3274.772729
9,0.000735,0.002232,2231.580814,735.056476
10,0.000379,0.000920,920.451460,379.125314
11,0.000810,0.001777,1777.158626,810.319713
12,0.001990,0.004375,4374.645057,1990.496562
13,0.000198,0.000460,459.968513,198.279862
14,0.002232,0.004873,4872.644707,2231.523448
15,0.000465,0.000981,980.742788,464.804443
16,0.000578,0.001314,1313.625964,578.459221
17,0.000701,0.001390,1390.387861,700.661045
18,0.000970,0.002226,2225.570528,970.231026
19,0.002062,0.004601,4601.150437,2062.298221
20,0.000412,0.000923,923.095707,412.303631
21,0.000411,0.000931,931.152907,410.839632
22,0.000406,0.000905,905.463450,406.132873
23,0.000437,0.000891,890.650740,437.088711
24,0.001404,0.002905,2904.980597,1403.742611
25,0.002352,0.005466,5466.416709,2351.637725
26,0.001010,0.001878,1878.371830,1010.237109
27,0.001344,0.003005,3005.352117,1344.337437
28,0.000285,0.000596,596.411187,285.128552
29,0.001105,0.001927,1927.109868,1105.142549
30,0.000552,0.001303,1303.218731,551.977335
31,0.000707,0.001729,1728.800690,706.648742
32,0.000506,0.001154,1153.625973,506.257869
33,0.004491,0.010822,10821.983198,4491.395347
34,0.000452,0.001078,1077.513823,451.626486
35,0.000536,0.001229,1229.304926,535.716364
36,0.000801,0.001495,1495.052429,801.386873
37,0.001054,0.001915,1914.660133,1054.334769
38,0.000692,0.001548,1547.517383,691.669476
39,0.000174,0.000410,409.816276,173.922281
40,0.000367,0.000787,786.610341,366.896739
41,0.000832,0.001867,1867.385772,831.616099
42,0.001972,0.004540,4540.418277,1972.374434
43,0.001097,0.002107,2107.077450,1096.826528
44,0.000365,0.000793,793.152475,364.879678
45,0.000245,0.000539,538.911305,245.072910
46,0.000501,0.001147,1147.434139,500.829351
47,0.000652,0.001512,1512.211352,652.448648
48,0.000376,0.001020,1019.645862,375.547378
49,0.000366,0.000977,976.919624,365.762356
50,0.000584,0.001393,1393.426698,584.227545
51,0.000437,0.001200,1200.285454,436.530459
52,0.000300,0.000690,689.748433,300.278232
53,0.001632,0.003335,3334.729017,1632.016993
54,0.001037,0.002387,2386.643199,1037.449651

In [93]:
updated_can_vars.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', '0', '1', '2', 'geometry_x', 'geometry_y',
       'ccsuid', 'geometry_z', 'CMA_da', 'downtown_da', 'CMA_not_downtown_da',
       'ccs_da', 'total_pop_downtown', 'total_pop_city',
       'pct_singlefam_downtown', 'pct_singlefam_city', 'pct_multifam_downtown',
       'pct_multifam_city', 'pct_mobile_home_and_others_downtown',
       'pct_mobile_home_and_others_city', 'pct_renter_downtown',
       'pct_renter_city', 'median_age_downtown', 'median_age_city',
       'bachelor_plus_downtown', 'bachelor_plus_city', 'median_hhinc_downtown',
       'median_hhinc_city', 'median_rent_downtown', 'median_rent_city',
       'pct_vacant_downtown', 'pct_vacant_city', 'pct_nhwhite_downtown',
       'pct_nhwhite_city', 'pct_nhblack_downtown', 'pct_nhblack_city',
       'pct_hisp_downtown', 'pct_hisp_city', 'pct_nhasian_downtown',
       'pct_nhasian_city', 'pct_commute_auto_downtown',
       'pct_commute_auto_city', 'pct_commute_public_transit_downtown',
       'pct_commute_public_transit_city', 'pct_commute_walk_downtown',
       'pct_commute_walk_city', 'pct_commute_bicycle_downtown',
       'pct_commute_bicycle_city', 'pct_commute_others_downtown',
       'pct_commute_others_city', 'housing_units_downtown',
       'housing_units_city', 'average_commute_time_downtown',
       'average_commute_time_city', 'land_area_downtown', 'land_area_city',
       'total_jobs', 'pct_jobs_agriculture_forestry_fishing_hunting',
       'pct_jobs_mining_quarrying_oil_gas', 'pct_jobs_utilities',
       'pct_jobs_construction', 'pct_jobs_manufacturing',
       'pct_jobs_wholesale_trade', 'pct_jobs_retail_trade',
       'pct_jobs_transport_warehouse', 'pct_jobs_information',
       'pct_jobs_finance_insurance', 'pct_jobs_real_estate',
       'pct_jobs_professional_science_techical',
       'pct_jobs_management_of_companies_enterprises',
       'pct_jobs_administrative_support_waste',
       'pct_jobs_educational_services',
       'pct_jobs_healthcare_social_assistance',
       'pct_jobs_arts_entertainment_recreation',
       'pct_jobs_accomodation_food_services', 'pct_jobs_other',
       'pct_jobs_public_administration', 'population_density_downtown',
       'population_density_city', 'employment_density_downtown',
       'housing_density_downtown', 'housing_density_city',
       'employment_entropy', 'pct_others_downtown', 'pct_others_city'],
      dtype='object')

In [101]:
updated_cols = updated_can_vars.columns[updated_can_vars.columns.str.contains("_city")].values.tolist()
updated_cols + ['0', 'pct_nhwhite_downtown',
 'pct_nhblack_downtown', 
       'pct_hisp_downtown', 'pct_nhasian_downtown',
        'population_density_downtown',
'employment_density_downtown', 'pct_mobile_home_and_others_downtown',
       'housing_density_downtown', 'pct_others_downtown', 'total_jobs']

['total_pop_city',
 'pct_singlefam_city',
 'pct_multifam_city',
 'pct_mobile_home_and_others_city',
 'pct_renter_city',
 'median_age_city',
 'bachelor_plus_city',
 'median_hhinc_city',
 'median_rent_city',
 'pct_vacant_city',
 'pct_nhwhite_city',
 'pct_nhblack_city',
 'pct_hisp_city',
 'pct_nhasian_city',
 'pct_commute_auto_city',
 'pct_commute_public_transit_city',
 'pct_commute_walk_city',
 'pct_commute_bicycle_city',
 'pct_commute_others_city',
 'housing_units_city',
 'average_commute_time_city',
 'land_area_city',
 'population_density_city',
 'housing_density_city',
 'pct_others_city',
 '0',
 'pct_nhwhite_downtown',
 'pct_nhblack_downtown',
 'pct_hisp_downtown',
 'pct_nhasian_downtown',
 'population_density_downtown',
 'employment_density_downtown',
 'pct_mobile_home_and_others_downtown',
 'housing_density_downtown',
 'pct_others_downtown',
 'total_jobs']

In [102]:
updated_can_vars_subset = updated_can_vars[updated_cols + ['0', 'pct_nhwhite_downtown',
 'pct_nhblack_downtown', 
       'pct_hisp_downtown', 'pct_nhasian_downtown',
        'population_density_downtown',
'employment_density_downtown', 'pct_mobile_home_and_others_downtown',
       'housing_density_downtown', 'pct_others_downtown', 'total_jobs']
]

In [103]:
updated_us_city_vars.columns

Index(['total_pop_city', 'pct_singlefam_city', 'pct_multifam_city',
       'pct_mobile_home_and_others_city', 'pct_renter_city', 'median_age_city',
       'bachelor_plus_city', 'median_hhinc_city', 'median_rent_city',
       'pct_vacant_city', 'pct_nhwhite_city', 'pct_nhblack_city',
       'pct_nhasian_city', 'pct_hisp_city', 'pct_others_city',
       'pct_commute_auto_city', 'pct_commute_public_transit_city',
       'pct_commute_bicycle_city', 'pct_commute_walk_city', 'pct_wfh_city',
       'pct_commute_others_city', 'housing_units_city',
       'average_commute_time_city', 'housing_density_city',
       'population_density_city', 'GEOID', 'city', 'display_title', 'state',
       'STATEFP', 'PLACEFP'],
      dtype='object')

In [113]:
updated_us_city_vars[['population_density_city', 'housing_density_city']] = updated_us_city_vars[['population_density_city', 'housing_density_city']] * 1000000
updated_us_downtown_vars[['population_density_downtown', 'housing_density_downtown', 'employment_density_downtown']] = updated_us_downtown_vars[['population_density_downtown_km2', 'housing_density_downtown_km2', 'employment_density_downtown_km2']]

In [114]:
us_city_index_with_features = updated_us_downtown_vars.merge(updated_us_city_vars, on = 'city', how = 'left')
us_city_index_with_features.head()

,Unnamed: 0.1,Unnamed: 0,_c0,city,total_pop_downtown,pct_singlefam_downtown,pct_multifam_downtown,pct_mobile_home_and_others_downtown,pct_renter_downtown,median_age_downtown,...,average_commute_time_city,housing_density_city,population_density_city,GEOID,display_title,state,STATEFP,PLACEFP,population_density_city_km2,housing_density_city_km2
0,0,0,0,New York,68267.0,1.732503,98.221000,0.046497,79.675599,36.388886,...,41.531562,4.491395e+09,1.082198e+10,3651000,"New York, NY",NY,36,51000,10821.983198,4491.395347
1,1,1,1,Los Angeles,49096.0,2.277189,97.351608,0.371203,95.097840,36.461569,...,31.954045,1.229309e+09,3.266067e+09,644000,"Los Angeles, CA",CA,6,44000,3266.066504,1229.308974
2,2,2,2,Chicago,21390.0,2.541991,97.342171,0.115838,63.414634,33.869771,...,35.061400,2.062298e+09,4.601150e+09,1714000,"Chicago, IL",IL,17,14000,4601.150437,2062.298221
3,3,3,3,Houston,16503.0,3.237135,96.762865,0.000000,83.800682,34.554093,...,27.693683,5.842275e+08,1.393427e+09,4835000,"Houston, TX",TX,48,35000,1393.426698,584.227545
4,4,4,4,Phoenix,15663.0,36.798770,62.948732,0.252498,67.757797,34.234687,...,26.217718,4.633395e+08,1.217973e+09,455000,"Phoenix, AZ",AZ,4,55000,1217.972794,463.339475

In [115]:
us_city_index_with_features[['city', 'average_commute_time_city']]

                city  average_commute_time_city
0           New York                  41.531562
1        Los Angeles                  31.954045
2            Chicago                  35.061400
3            Houston                  27.693683
4            Phoenix                  26.217718
5       Philadelphia                  33.619914
6        San Antonio                  24.741490
7          San Diego                  24.460038
8             Dallas                  27.115995
9           San Jose                  30.920240
10            Austin                  24.523028
11      Jacksonville                  25.159106
12        Fort Worth                  27.234607
13          Columbus                  21.985649
14      Indianapolis                  23.619980
15         Charlotte                  25.878967
16     San Francisco                  33.843621
17           Seattle                  27.909959
18            Denver                  25.908058
19     Washington DC                  30.803222
20         Nashville                  25.007779
21     Oklahoma City                  21.413723
22           El Paso                  23.201616
23            Boston                  30.896197
24          Portland                  26.521823
25         Las Vegas                  26.091985
26           Detroit                  25.909420
27           Memphis                  21.700893
28        Louisville                  22.845056
29         Baltimore                  31.376869
30         Milwaukee                  22.244116
31       Albuquerque                  21.819749
32            Tucson                  22.512775
33            Fresno                  22.217465
34        Sacramento                  26.241006
35       Kansas City                  22.007356
36           Atlanta                  27.196934
37             Omaha                  19.160103
38  Colorado Springs                  22.722995
39           Raleigh                  23.953002
40             Miami                  29.258822
41           Oakland                  33.410087
42       Minneapolis                  23.221069
43             Tulsa                  18.640797
44       Bakersfield                  23.031718
45           Wichita                  18.571397
46             Tampa                  24.568808
47       New Orleans                  24.163119
48         Cleveland                  24.037319
49          Honolulu                  23.663883
50        Cincinnati                  23.248900
51        Pittsburgh                  24.269921
52    Salt Lake City                  19.544851
53          St Louis                  24.384129
54           Orlando                  26.068035

In [116]:
updated_can_vars_subset.columns

Index(['total_pop_city', 'pct_singlefam_city', 'pct_multifam_city',
       'pct_mobile_home_and_others_city', 'pct_renter_city', 'median_age_city',
       'bachelor_plus_city', 'median_hhinc_city', 'median_rent_city',
       'pct_vacant_city', 'pct_nhwhite_city', 'pct_nhblack_city',
       'pct_hisp_city', 'pct_nhasian_city', 'pct_commute_auto_city',
       'pct_commute_public_transit_city', 'pct_commute_walk_city',
       'pct_commute_bicycle_city', 'pct_commute_others_city',
       'housing_units_city', 'average_commute_time_city', 'land_area_city',
       'population_density_city', 'housing_density_city', 'pct_others_city',
       'city', 'pct_nhwhite_downtown', 'pct_nhblack_downtown',
       'pct_hisp_downtown', 'pct_nhasian_downtown',
       'population_density_downtown', 'employment_density_downtown',
       'pct_mobile_home_and_others_downtown', 'housing_density_downtown',
       'pct_others_downtown', 'total_jobs'],
      dtype='object')

In [117]:
updated_can_vars = updated_can_vars.rename(columns = {"0": 'city'})
updated_can_vars.head()

,Unnamed: 0.1,Unnamed: 0,city,1,2,geometry_x,geometry_y,ccsuid,geometry_z,CMA_da,...,pct_jobs_other,pct_jobs_public_administration,population_density_downtown,population_density_city,employment_density_downtown,housing_density_downtown,housing_density_city,employment_entropy,pct_others_downtown,pct_others_city
0,0,0,Toronto,ON,Toronto,"MULTIPOLYGON (((7204453.214285 979658.325715, ...","POLYGON ((7223838.448570004 931133.854285, 722...",3520005,"MULTIPOLYGON (((7239903.86857 950427.517145, 7...","[35180487, 35180488, 35180489, 35180490, 35180...",...,7.973287,0.522648,9309.462669,4305.525108,594.190186,5254.718498,1754.209595,2.483573,5.585844,8.818148
1,1,1,Montreal,QC,Montréal,"MULTIPOLYGON (((7632208.177145 1268333.72, 763...",MULTIPOLYGON (((7635644.96857 1244991.62571500...,2466023,"MULTIPOLYGON (((7632208.177145 1268333.72, 763...","[24580103, 24580104, 24580105, 24580106, 24580...",...,9.035745,0.900730,5076.708017,4656.205595,487.872797,2871.635843,2129.961391,2.532189,1.456219,2.425115
2,2,2,Calgary,AB,Calgary,"POLYGON ((4686213.557145 1938649.662855, 46866...","POLYGON ((4686053.488569997 1923856.597144998,...",4806016,"POLYGON ((4684997.491429999 1940795.817145, 46...","[48060566, 48060567, 48060568, 48060569, 48060...",...,4.956473,0.758214,4012.106641,1459.536562,563.994621,2383.237592,549.702395,2.506339,4.610330,7.032039
3,3,3,Ottawa,ON,Ottawa - Gatineau (Ontario part / partie de l'...,"POLYGON ((7492423.625715 1207910.002855, 74924...","POLYGON ((7471074.63143 1192567.648570001, 747...",3506008,"POLYGON ((7497307.95143 1207692.14857, 7497411...","[24810310, 24810318, 24810372, 35060078, 35060...",...,15.572859,3.203560,3080.325081,323.035681,180.954053,1730.838596,129.234258,2.404843,2.003177,2.454028
4,4,4,Edmonton,AB,Edmonton,"POLYGON ((4816202.74857 2184876.16857, 4816133...","POLYGON ((4815855.474284997 2169718.845714999,...",4811061,"POLYGON ((4832282.265715 2178112.697145, 48320...","[48111608, 48111609, 48111610, 48111611, 48111...",...,10.685805,5.163477,2847.607062,1331.180387,201.166090,1573.114008,515.066456,2.511963,4.983959,7.430617

In [118]:
updated_can_vars_subset = updated_can_vars_subset.rename(columns = {"0": 'city'})
updated_can_vars_subset.head()

,total_pop_city,pct_singlefam_city,pct_multifam_city,pct_mobile_home_and_others_city,pct_renter_city,median_age_city,bachelor_plus_city,median_hhinc_city,median_rent_city,pct_vacant_city,...,pct_nhwhite_downtown,pct_nhblack_downtown,pct_hisp_downtown,pct_nhasian_downtown,population_density_downtown,employment_density_downtown,pct_mobile_home_and_others_downtown,housing_density_downtown,pct_others_downtown,total_jobs
0,2731571.0,36.425472,63.565543,0.008536,47.247805,40.6,36.397963,50910.030196,928.814751,5.608550,...,58.653276,6.054519,2.171210,27.535151,9309.462669,594.190186,0.000000,5254.718498,5.585844,17220.0
1,1704694.0,14.302294,85.645770,0.051936,63.269193,40.3,31.311946,38843.945475,595.493221,7.592384,...,72.014040,5.492837,3.220757,17.816146,5076.708017,487.872797,0.008054,2871.635843,1.456219,10547.0
2,1239220.0,72.225615,27.339440,0.434946,28.554441,37.6,33.242481,75274.983353,1011.565108,4.681916,...,68.508060,4.425506,2.433515,20.022590,4012.106641,563.994621,0.000000,2383.237592,4.610330,7122.0
3,934243.0,69.074661,30.709957,0.214044,34.323287,40.1,37.653332,66494.938497,859.985015,5.613596,...,78.607446,7.536092,1.464392,10.388893,3080.325081,180.954053,0.011629,1730.838596,2.003177,4495.0
4,932546.0,66.127624,33.139333,0.734428,35.704289,37.7,27.319553,67457.008065,952.789154,6.991107,...,68.865179,9.542640,1.708573,14.899649,2847.607062,201.166090,0.000000,1573.114008,4.983959,5016.0

In [119]:
in_both = np.intersect1d(us_city_index_with_features.columns.values, updated_can_vars.columns.values)
in_both

array(['Unnamed: 0', 'Unnamed: 0.1', 'average_commute_time_city',
       'average_commute_time_downtown', 'bachelor_plus_city',
       'bachelor_plus_downtown', 'city', 'employment_density_downtown',
       'employment_entropy', 'housing_density_city',
       'housing_density_downtown', 'housing_units_city',
       'housing_units_downtown', 'median_age_city', 'median_age_downtown',
       'median_hhinc_city', 'median_hhinc_downtown', 'median_rent_city',
       'median_rent_downtown', 'pct_commute_auto_city',
       'pct_commute_auto_downtown', 'pct_commute_bicycle_city',
       'pct_commute_bicycle_downtown', 'pct_commute_others_city',
       'pct_commute_others_downtown', 'pct_commute_public_transit_city',
       'pct_commute_public_transit_downtown', 'pct_commute_walk_city',
       'pct_commute_walk_downtown', 'pct_hisp_city', 'pct_hisp_downtown',
       'pct_jobs_accomodation_food_services',
       'pct_jobs_administrative_support_waste',
       'pct_jobs_agriculture_forestry_fishing_hunting',
       'pct_jobs_arts_entertainment_recreation', 'pct_jobs_construction',
       'pct_jobs_educational_services', 'pct_jobs_finance_insurance',
       'pct_jobs_healthcare_social_assistance', 'pct_jobs_information',
       'pct_jobs_management_of_companies_enterprises',
       'pct_jobs_manufacturing', 'pct_jobs_mining_quarrying_oil_gas',
       'pct_jobs_other', 'pct_jobs_professional_science_techical',
       'pct_jobs_public_administration', 'pct_jobs_real_estate',
       'pct_jobs_retail_trade', 'pct_jobs_transport_warehouse',
       'pct_jobs_utilities', 'pct_jobs_wholesale_trade',
       'pct_mobile_home_and_others_city',
       'pct_mobile_home_and_others_downtown', 'pct_multifam_city',
       'pct_multifam_downtown', 'pct_nhasian_city',
       'pct_nhasian_downtown', 'pct_nhblack_city', 'pct_nhblack_downtown',
       'pct_nhwhite_city', 'pct_nhwhite_downtown', 'pct_others_city',
       'pct_others_downtown', 'pct_renter_city', 'pct_renter_downtown',
       'pct_singlefam_city', 'pct_singlefam_downtown', 'pct_vacant_city',
       'pct_vacant_downtown', 'population_density_city',
       'population_density_downtown', 'total_jobs', 'total_pop_city',
       'total_pop_downtown'], dtype=object)

In [120]:

# change them back to original variables so modeling is easier
updated_us_vars = pd.concat([us_city_index_with_features[in_both]]).drop(columns = ["Unnamed: 0", "Unnamed: 0.1"])

updated_us_vars.head()

,average_commute_time_city,average_commute_time_downtown,bachelor_plus_city,bachelor_plus_downtown,city,employment_density_downtown,employment_entropy,housing_density_city,housing_density_downtown,housing_units_city,...,pct_renter_downtown,pct_singlefam_city,pct_singlefam_downtown,pct_vacant_city,pct_vacant_downtown,population_density_city,population_density_downtown,total_jobs,total_pop_city,total_pop_downtown
0,41.531562,27.254815,22.168144,78.794374,New York,239818.342661,2.479315,4.491395e+09,10190.825085,3494228,...,79.675599,16.078773,1.732503,9.363842,20.108762,1.082198e+10,14064.146203,1164072.0,8419316,68267.0
1,31.954045,32.424316,22.618101,36.028993,Los Angeles,77725.149732,2.497852,1.229309e+09,5997.613542,1493108,...,95.097840,43.657994,2.277189,7.316216,12.263983,3.266067e+09,10510.005870,363082.0,3966936,49096.0
2,35.061400,23.429021,23.250899,88.995993,Chicago,262660.307882,2.438863,2.062298e+09,6627.928750,1214450,...,63.414634,29.427724,2.541991,12.155379,17.678100,4.601150e+09,9123.585556,615800.0,2709534,21390.0
3,27.693683,18.465414,20.015301,35.894253,Houston,35428.026207,2.640123,5.842275e+08,1183.904967,968704,...,83.800682,49.132656,3.237135,11.389444,19.407543,1.393427e+09,2983.353743,195977.0,2310432,16503.0
4,26.217718,19.184081,18.273274,45.999625,Phoenix,17412.165238,2.494974,4.633395e+08,903.818043,621230,...,67.757797,65.233810,36.798770,8.917470,21.857504,1.217973e+09,1554.122518,175486.0,1633017,15663.0

In [141]:
updated_us_vars[['city', 'average_commute_time_city']]

                city  average_commute_time_city
0           New York                  41.531562
1        Los Angeles                  31.954045
2            Chicago                  35.061400
3            Houston                  27.693683
4            Phoenix                  26.217718
5       Philadelphia                  33.619914
6        San Antonio                  24.741490
7          San Diego                  24.460038
8             Dallas                  27.115995
9           San Jose                  30.920240
10            Austin                  24.523028
11      Jacksonville                  25.159106
12        Fort Worth                  27.234607
13          Columbus                  21.985649
14      Indianapolis                  23.619980
15         Charlotte                  25.878967
16     San Francisco                  33.843621
17           Seattle                  27.909959
18            Denver                  25.908058
19     Washington DC                  30.803222
20         Nashville                  25.007779
21     Oklahoma City                  21.413723
22           El Paso                  23.201616
23            Boston                  30.896197
24          Portland                  26.521823
25         Las Vegas                  26.091985
26           Detroit                  25.909420
27           Memphis                  21.700893
28        Louisville                  22.845056
29         Baltimore                  31.376869
30         Milwaukee                  22.244116
31       Albuquerque                  21.819749
32            Tucson                  22.512775
33            Fresno                  22.217465
34        Sacramento                  26.241006
35       Kansas City                  22.007356
36           Atlanta                  27.196934
37             Omaha                  19.160103
38  Colorado Springs                  22.722995
39           Raleigh                  23.953002
40             Miami                  29.258822
41           Oakland                  33.410087
42       Minneapolis                  23.221069
43             Tulsa                  18.640797
44       Bakersfield                  23.031718
45           Wichita                  18.571397
46             Tampa                  24.568808
47       New Orleans                  24.163119
48         Cleveland                  24.037319
49          Honolulu                  23.663883
50        Cincinnati                  23.248900
51        Pittsburgh                  24.269921
52    Salt Lake City                  19.544851
53          St Louis                  24.384129
54           Orlando                  26.068035

In [121]:
original_model_data[['city', 'pct_hisp_downtown', 'pct_hisp_city']]

            city  pct_hisp_downtown  pct_hisp_city
0        Halifax           0.077640       0.017530
1         London           0.030308       0.077199
2       Portland          15.444015      15.444015
3      Las Vegas          58.027329      58.027329
4        Detroit           5.160839       5.160839
..           ...                ...            ...
61     San Diego          20.199713      20.199713
62        Dallas          14.099454      14.099454
63      San Jose          15.282392      15.282392
64        Austin          12.850295      12.850295
65  Jacksonville           5.135674       5.135674

[66 rows x 3 columns]

In [122]:
var_in_both2_us = np.intersect1d(updated_us_vars.drop(columns = 'city').columns.values, original_model_data.drop(columns = 'city').columns.values)
in_both2_us= np.intersect1d(updated_us_vars.columns.values, original_model_data.columns.values)

In [123]:
both_data = updated_us_vars[in_both2_us].melt(id_vars = 'city', value_name = 'updated').merge(original_model_data[in_both2_us].melt(id_vars = 'city', value_name = 'original'), how = 'inner', on = ['city', 'variable'])

In [124]:
both_data['difference'] = both_data['updated'] - both_data['original']
both_data['pct_of_og'] = 100 * abs(both_data['difference'] / both_data['original'])
changed_variables = both_data[both_data['variable'].str.contains('_city') & ~both_data['variable'].str.contains('density') & ~both_data['variable'].str.contains('pct_hisp')]
changed_variables.groupby('variable')[['difference', 'pct_of_og']].mean().sort_values(by = 'pct_of_og', ascending = False)

                                    difference  pct_of_og
variable
bachelor_plus_city                  -14.762286  39.607815
total_pop_city                  -524136.436364  39.554675
housing_units_city              -203217.127273  37.221597
pct_mobile_home_and_others_city      -0.749016  36.383119
pct_commute_bicycle_city              0.262221  32.415651
pct_commute_public_transit_city       1.528670  30.769237
pct_commute_walk_city                 0.838693  28.353863
pct_nhblack_city                      4.270890  21.551615
pct_multifam_city                     5.994051  17.425787
pct_vacant_city                       1.212150  14.064860
pct_renter_city                       6.021183  13.768290
median_hhinc_city                 -8559.951930  13.505012
pct_nhwhite_city                     -5.215562  12.862340
pct_nhasian_city                      0.001693  12.235892
pct_singlefam_city                   -5.245035   9.642465
median_rent_city                    -76.617270   6.700531
pct_commute_others_city               0.002011   6.385671
median_age_city                      -1.474567   4.199884
pct_commute_auto_city                -2.631595   4.022468
average_commute_time_city            -0.446843   2.835015

In [125]:
var_in_both2_can = np.intersect1d(updated_can_vars_subset.drop(columns = 'city').columns.values, original_model_data.drop(columns = 'city').columns.values)
in_both2_can= np.intersect1d(updated_can_vars_subset.columns.values, original_model_data.columns.values)

In [126]:
both_data_can = updated_can_vars_subset[in_both2_can].melt(id_vars = 'city', value_name = 'updated').merge(original_model_data[in_both2_can].melt(id_vars = 'city', value_name = 'original'), how = 'inner', on = ['city', 'variable'])

In [127]:
both_data_can['difference'] = both_data_can['updated'] - both_data_can['original']
both_data_can['pct_of_og'] = 100 * abs(both_data_can['difference'] / both_data_can['original'])
both_data_can.sort_values(by = 'difference', ascending = False)

,city,variable,updated,original,difference,pct_of_og
326,Vancouver,population_density_downtown,9.482680e+03,2.456004e-02,9482.655200,3.861010e+07
319,Toronto,population_density_downtown,9.309463e+03,2.411141e-02,9309.438557,3.861010e+07
324,Mississauga,population_density_downtown,6.178622e+03,1.600256e-02,6178.606160,3.861010e+07
51,Vancouver,housing_density_downtown,5.609451e+03,1.452842e-02,5609.436884,3.861010e+07
315,Vancouver,population_density_city,5.427540e+03,8.656561e-03,5427.531559,6.269847e+07
...,...,...,...,...,...,...
330,Toronto,total_pop_city,2.731571e+06,2.808905e+06,-77334.000000,2.753172e+00
56,Montreal,housing_units_city,7.798050e+05,8.703600e+05,-90555.000000,1.040432e+01
60,Mississauga,housing_units_city,2.409150e+05,4.229100e+05,-181995.000000,4.303398e+01
331,Montreal,total_pop_city,1.704694e+06,1.942717e+06,-238023.000000,1.225207e+01
335,Mississauga,total_pop_city,7.215990e+05,1.358376e+06,-636777.000000,4.687782e+01

In [129]:

# now join this to original model data

original_model_data_subset_us = original_model_data.drop(columns = var_in_both2_us)


original_model_data_subset_us.columns

Index(['city', 'median_year_structure_built', 'median_no_rooms',
       '%Liberal-Leaning', '%Conservative-Leaning', '%Other',
       'days_school_closing', 'days_workplace_closing',
       'days_cancel_large_events', 'days_cancel_all_events',
       'days_stay_home_requirements', 'days_income_support',
       'days_mask_mandates', 'winter_avg_temp', 'spring_avg_temp',
       'summer_avg_temp', 'fall_avg_temp'],
      dtype='object')

In [130]:
updated_us_data_full = updated_us_vars.merge(original_model_data_subset_us, how = 'left', on = 'city')
updated_us_data_full

,average_commute_time_city,average_commute_time_downtown,bachelor_plus_city,bachelor_plus_downtown,city,employment_density_downtown,employment_entropy,housing_density_city,housing_density_downtown,housing_units_city,...,days_workplace_closing,days_cancel_large_events,days_cancel_all_events,days_stay_home_requirements,days_income_support,days_mask_mandates,winter_avg_temp,spring_avg_temp,summer_avg_temp,fall_avg_temp
0,41.531562,27.254815,22.168144,78.794374,New York,239818.342661,2.479315,4.491395e+09,10190.825085,3494228,...,358,308,458,78,549,710,37.900000,54.083333,77.450000,60.983333
1,31.954045,32.424316,22.618101,36.028993,Los Angeles,77725.149732,2.497852,1.229309e+09,5997.613542,1493108,...,455,478,491,156,768,836,63.333333,66.550000,78.200000,74.200000
2,35.061400,23.429021,23.250899,88.995993,Chicago,262660.307882,2.438863,2.062298e+09,6627.928750,1214450,...,69,178,450,144,869,816,31.933333,50.083333,73.083333,57.933333
3,27.693683,18.465414,20.015301,35.894253,Houston,35428.026207,2.640123,5.842275e+08,1183.904967,968704,...,340,353,408,62,728,679,60.900000,74.933333,88.866667,75.500000
4,26.217718,19.184081,18.273274,45.999625,Phoenix,17412.165238,2.494974,4.633395e+08,903.818043,621230,...,234,195,246,46,546,668,63.250000,77.783333,96.566667,82.883333
5,33.619914,25.873410,17.313194,77.576036,Philadelphia,57529.375698,2.566149,1.972374e+09,6673.024285,685956,...,214,200,369,74,533,735,39.750000,56.950000,78.516667,62.183333
6,24.741490,0.000000,16.566697,48.024055,San Antonio,25061.674074,2.499787,4.365305e+08,529.745793,548473,...,340,353,408,62,728,679,60.100000,75.566667,88.716667,75.450000
7,24.460038,24.147055,27.007532,53.313343,San Diego,9420.294962,2.499829,6.474159e+08,2329.054222,546431,...,455,478,491,156,768,836,62.400000,63.333333,72.933333,71.133333
8,27.115995,22.375326,21.016508,75.398363,Dallas,48202.845309,2.555314,6.524486e+08,2455.315707,574097,...,340,353,408,62,728,679,54.200000,69.816667,90.266667,72.850000
9,30.920240,32.561224,25.666215,70.658372,San Jose,36816.817567,2.092584,7.350565e+08,1601.175558,338509,...,455,478,491,156,768,836,55.183333,60.566667,75.333333,68.383333
10,24.523028,20.795858,32.315272,77.980029,Austin,44856.511367,2.407723,5.008294e+08,1917.907399,415006,...,340,353,408,62,728,679,57.366667,73.133333,88.800000,73.883333
11,25.159106,0.000000,19.133920,19.890045,Jacksonville,17065.717277,2.297479,1.982799e+08,471.038613,383856,...,224,193,337,368,421,739,62.900000,73.966667,86.016667,75.933333
12,27.234607,23.519264,19.980705,42.125318,Fort Worth,10528.496445,2.565010,3.657624e+08,383.630512,327379,...,340,353,408,62,728,679,37.166667,52.866667,69.050000,52.466667
13,21.985649,19.412109,23.820005,73.705776,Columbus,11086.341196,2.587033,6.916695e+08,810.569365,392673,...,190,158,447,142,644,720,35.700000,56.833333,75.400000,58.483333
14,23.619980,19.659319,20.034187,51.867400,Indianapolis,52710.150007,2.479227,4.123036e+08,1551.258529,386108,...,95,129,480,18,651,723,35.733333,57.516667,76.033333,58.250000
15,25.878967,19.373118,28.901739,73.558974,Charlotte,26777.842101,2.366622,4.516265e+08,1911.162551,359379,...,374,69,422,155,688,657,48.333333,64.216667,81.683333,65.900000
16,33.843621,30.391523,34.760330,79.095644,San Francisco,153261.406627,2.394690,3.274773e+09,4821.498367,397812,...,455,478,491,156,768,836,55.250000,59.266667,67.216667,65.850000
17,27.909959,23.069554,36.659037,52.643604,Seattle,82801.157449,2.634187,1.632017e+09,6074.239054,354475,...,350,482,476,70,545,752,42.816667,53.000000,68.600000,56.033333
18,25.908058,25.402516,30.174281,75.742027,Denver,57503.397612,2.579934,8.103197e+08,4055.872064,321717,...,308,303,476,62,635,797,35.516667,50.800000,74.500000,57.750000
19,30.803222,22.185928,24.767464,80.837784,Washington DC,115823.586243,2.197065,1.990497e+09,4701.658373,315176,...,401,402,434,58,422,737,42.216667,60.166667,79.600000,63.400000
20,25.007779,0.000000,25.789406,56.877828,Nashville,53951.859304,2.414944,2.450729e+08,1875.698636,301844,...,310,303,400,54,569,654,45.200000,62.966667,80.750000,64.516667
21,21.413723,0.000000,19.700352,25.381904,Oklahoma City,23521.388505,2.612688,1.739223e+08,657.133602,273177,...,55,237,108,38,603,685,47.083333,64.266667,85.966667,68.266667
22,23.201616,31.020607,16.725090,4.077027,El Paso,4221.257441,2.625477,3.755474e+08,820.200240,250383,...,340,353,408,62,728,679,52.316667,69.900000,86.316667,70.450000
23,30.896197,22.766241,27.026542,76.318141,Boston,248208.240568,2.323738,2.351638e+09,4609.559826,294418,...,426,214,442,0,721,744,35.066667,51.616667,74.200000,58.466667
24,26.521823,0.000000,30.090127,19.112988,Portland,140116.630488,2.595834,8.316161e+08,596.670764,287372,...,400,410,471,89,538,792,43.450000,53.066667,70.566667,57.750000
25,26.091985,28.180595,15.969204,8.219663,Las Vegas,4010.364379,2.050998,7.066487e+08,1331.133761,259464,...,281,190,434,38,537,709,46.400000,66.200000,88.533333,70.333333
26,25.909420,19.618899,9.064044,53.615702,Detroit,29929.889947,2.539730,1.010237e+09,1613.171194,362947,...,362,167,466,58,539,642,31.316667,51.100000,74.333333,57.350000
27,21.700893,19.725969,15.699460,66.030203,Memphis,10550.385203,2.247232,3.648797e+08,1264.221394,299913,...,310,303,400,54,569,654,47.966667,65.500000,83.533333,67.600000
28,22.845056,0.000000,17.937636,18.854869,Louisville,21878.599638,2.441432,4.061329e+08,897.069028,277101,...,121,109,418,57,436,740,39.966667,59.950000,78.966667,60.300000
29,31.376869,30.223025,16.764785,44.389394,Baltimore,18630.348764,2.448787,1.403743e+09,2943.392732,294296,...,188,322,429,63,752,806,40.283333,57.350000,77.733333,61.450000
30,22.244116,20.392892,15.942571,67.287234,Milwaukee,18759.236526,2.552261,1.037450e+09,3268.122706,258444,...,70,70,442,55,552,679,28.083333,49.050000,70.800000,55.166667
31,21.819749,18.961627,19.446649,28.342436,Albuquerque,5326.984234,2.472569,5.062579e+08,638.594586,245476,...,429,380,476,0,538,806,40.683333,59.683333,78.066667,60.900000
32,22.512775,19.990454,16.549612,46.645367,Tucson,9474.458183,2.158535,3.881672e+08,854.882495,239287,...,234,195,246,46,546,668,57.433333,71.216667,87.766667,74.750000
33,22.217465,0.000000,14.548902,13.050426,Fresno,8542.717259,2.410253,6.018499e+08,429.198047,178831,...,455,478,491,156,768,836,54.166667,65.516667,85.616667,71.333333
34,26.241006,22.048493,21.202525,40.126939,Sacramento,28381.834012,1.793472,7.769139e+08,2071.392254,196652,...,455,478,491,156,768,836,52.716667,63.683333,81.466667,70.683333
35,22.007356,19.529955,22.242881,49.008471,Kansas City,15330.159712,2.697732,2.851286e+08,1508.014196,232537,...,70,345,395,239,421,656,38.500000,59.783333,80.300000,62.450000
36,27.196934,19.833333,28.915750,23.672401,Atlanta,54369.542696,2.446575,7.006610e+08,580.139115,246322,...,100,278,371,316,421,716,50.233333,65.966667,82.666667,68.016667
37,19.160103,16.159348,24.337299,49.544023,Omaha,8995.287824,2.613695,5.519773e+08,1090.971046,201551,...,105,244,152,13,709,724,69.216667,64.133333,55.666667,59.433333
38,22.722995,20.548135,24.338817,41.308567,Colorado Springs,3382.461961,2.492371,3.791253e+08,613.549132,191476,...,308,303,476,62,635,797,32.466667,46.633333,66.983333,51.750000
39,23.953002,24.337668,32.380959,43.162510,Raleigh,11387.057083,2.279491,5.357164e+08,1048.371860,202417,...,374,69,422,155,688,657,48.000000,63.716667,81.250000,65.983333
40,29.258822,23.078683,17.914673,76.370065,Miami,75076.270188,2.352899,2.231523e+09,15499.090077,208046,...,224,193,337,368,421,739,73.133333,78.250000,85.500000,81.766667
41,33.410087,33.629319,25.233248,53.940520,Oakland,39158.424919,2.597488,1.197127e+09,4225.579843,173300,...,455,478,491,156,768,836,54.900000,58.933333,67.183333,65.366667
42,23.221069,17.937453,30.383277,58.162291,Minneapolis,87134.966395,2.428133,1.344337e+09,1766.150232,188017,...,130,235,441,52,685,692,21.216667,51.400000,74.366667,54.183333
43,18.640797,0.000000,20.699733,35.561619,Tulsa,11028.082817,2.663565,3.668967e+08,985.941229,187655,...,55,237,108,38,603,685,46.133333,63.400000,84.583333,67.350000
44,23.031718,17.391359,14.328841,19.647286,Bakersfield,5145.831654,2.609902,3.209262e+08,491.459982,124478,...,455,478,491,156,768,836,54.016667,63.416667,83.883333,69.466667
45,18.571397,0.000000,19.062121,48.371777,Wichita,18912.266481,2.526406,4.108396e+08,547.021602,172020,...,118,178,389,35,627,669,42.116667,61.183333,84.466667,65.566667
46,24.568808,22.247996,23.316774,54.101208,Tampa,15418.360418,2.286555,5.784592e+08,1509.590451,170820,...,224,193,337,368,421,739,67.283333,75.950000,85.950000,78.633333
47,24.163119,16.441748,21.245910,57.842102,New Orleans,12617.560934,2.480455,4.370887e+08,1745.515962,191808,...,578,409,689,58,528,718,61.533333,74.583333,86.483333,75.166667
48,24.037319,19.554184,10.920216,37.418862,Cleveland,14106.512411,2.633707,1.054335e+09,641.011106,212161,...,190,158,447,142,644,720,33.066667,50.350000,71.866667,57.433333
49,23.663883,21.824892,23.656573,41.566882,Honolulu,10672.543857,2.684678,9.702310e+08,1376.961170,152139,...,475,468,699,397,564,732,74.066667,75.483333,79.483333,78.850000
50,23.248900,18.805942,21.430885,63.739557,Cincinnati,15386.647286,2.631970,8.013869e+08,1517.493058,161555,...,190,158,447,142,644,720,38.050000,58.383333,77.133333,59.616667
51,24.269921,18.719340,23.229789,38.256379,Pittsburgh,20548.305824,2.512868,1.096827e+09,1172.733930,157311,...,214,200,369,74,533,735,35.033333,55.066667,73.633333,57.200000
52,19.544851,19.903407,25.739708,43.906120,Salt Lake City,10648.095305,2.681782,3.002782e+08,1313.214464,86092,...,78,132,300,0,421,663,32.633333,48.933333,74.750000,55.250000
53,24.384129,20.075982,19.742603,60.822117,St Louis,54733.255898,2.482826,1.105143e+09,2779.095639,176729,...,70,345,395,239,421,656,82.283333,85.466667,86.350000,88.833333
54,26.068035,23.039271,25.409288,58.580270,Orlando,20121.051447,2.386851,4.648044e+08,1551.166002,133095,...,224,193,337,368,421,739,67.300000,76.100000,85.983333,78.066667

In [131]:

# now join this to original model data

original_model_data_subset_can = original_model_data.drop(columns = var_in_both2_can)


original_model_data_subset_can.columns

Index(['city', 'total_pop_downtown', 'pct_singlefam_downtown',
       'pct_multifam_downtown', 'pct_renter_downtown', 'median_age_downtown',
       'bachelor_plus_downtown', 'median_hhinc_downtown',
       'median_rent_downtown', 'pct_vacant_downtown',
       'pct_commute_auto_downtown', 'pct_commute_public_transit_downtown',
       'pct_commute_bicycle_downtown', 'pct_commute_walk_downtown',
       'pct_commute_others_downtown', 'housing_units_downtown',
       'average_commute_time_downtown',
       'pct_jobs_agriculture_forestry_fishing_hunting',
       'pct_jobs_mining_quarrying_oil_gas', 'pct_jobs_utilities',
       'pct_jobs_construction', 'pct_jobs_manufacturing',
       'pct_jobs_wholesale_trade', 'pct_jobs_retail_trade',
       'pct_jobs_transport_warehouse', 'pct_jobs_information',
       'pct_jobs_finance_insurance', 'pct_jobs_real_estate',
       'pct_jobs_professional_science_techical',
       'pct_jobs_management_of_companies_enterprises',
       'pct_jobs_administrative_support_waste',
       'pct_jobs_educational_services',
       'pct_jobs_healthcare_social_assistance',
       'pct_jobs_arts_entertainment_recreation',
       'pct_jobs_accomodation_food_services', 'pct_jobs_other',
       'pct_jobs_public_administration', 'employment_entropy',
       'median_year_structure_built', 'median_no_rooms', '%Liberal-Leaning',
       '%Conservative-Leaning', '%Other', 'days_school_closing',
       'days_workplace_closing', 'days_cancel_large_events',
       'days_cancel_all_events', 'days_stay_home_requirements',
       'days_income_support', 'days_mask_mandates', 'winter_avg_temp',
       'spring_avg_temp', 'summer_avg_temp', 'fall_avg_temp'],
      dtype='object')

In [132]:
updated_can_data_full = updated_can_vars_subset.merge(original_model_data_subset_can, how = 'left', on = 'city')
updated_can_data_full

,total_pop_city,pct_singlefam_city,pct_multifam_city,pct_mobile_home_and_others_city,pct_renter_city,median_age_city,bachelor_plus_city,median_hhinc_city,median_rent_city,pct_vacant_city,...,days_workplace_closing,days_cancel_large_events,days_cancel_all_events,days_stay_home_requirements,days_income_support,days_mask_mandates,winter_avg_temp,spring_avg_temp,summer_avg_temp,fall_avg_temp
0,2731571.0,36.425472,63.565543,0.008536,47.247805,40.6,36.397963,50910.030196,928.814751,5.608550,...,496.0,365.0,718.0,127.0,802.0,772.0,29.933333,47.216667,71.400000,55.816667
1,1704694.0,14.302294,85.645770,0.051936,63.269193,40.3,31.311946,38843.945475,595.493221,7.592384,...,487.0,471.0,718.0,219.0,779.0,808.0,21.716667,45.950000,70.216667,52.800000
2,1239220.0,72.225615,27.339440,0.434946,28.554441,37.6,33.242481,75274.983353,1011.565108,4.681916,...,602.0,277.0,642.0,0.0,667.0,786.0,22.150000,43.433333,64.250000,46.250000
3,934243.0,69.074661,30.709957,0.214044,34.323287,40.1,37.653332,66494.938497,859.985015,5.613596,...,496.0,365.0,718.0,127.0,802.0,772.0,20.950000,44.700000,68.000000,50.783333
4,932546.0,66.127624,33.139333,0.734428,35.704289,37.7,27.319553,67457.008065,952.789154,6.991107,...,602.0,277.0,642.0,0.0,667.0,786.0,16.983333,41.000000,64.233333,44.266667
5,721599.0,62.972418,36.888529,0.139053,27.721396,39.6,33.516881,64203.449647,976.763556,3.041023,...,496.0,365.0,718.0,127.0,802.0,772.0,31.133333,47.850000,70.550000,55.916667
6,705244.0,66.866516,32.909321,0.222384,35.102919,39.9,26.074443,52899.905596,706.858187,4.485718,...,325.0,501.0,672.0,253.0,654.0,715.0,10.483333,44.183333,69.583333,48.566667
7,631486.0,19.824595,80.164838,0.008805,53.096878,41.6,39.956557,50521.799551,932.681590,8.241925,...,355.0,445.0,689.0,12.0,667.0,673.0,40.666667,50.483333,64.316667,52.933333
8,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,531902.0,39.987700,59.486589,0.527694,46.587843,43.2,25.748890,46310.038405,575.385658,5.392460,...,487.0,471.0,718.0,219.0,779.0,808.0,16.250000,38.616667,64.083333,47.333333
10,403131.0,60.729843,36.968123,2.304919,39.859232,40.8,29.146698,53790.051957,743.979842,7.480597,...,175.0,214.0,736.0,40.0,667.0,700.0,31.716667,41.883333,64.550000,53.816667
11,383822.0,66.062891,33.845164,0.088881,39.885987,40.5,25.346569,47957.311861,676.696842,7.073446,...,496.0,365.0,718.0,127.0,802.0,772.0,28.483333,48.650000,68.950000,53.566667

In [133]:
all_data_updated = pd.concat([updated_can_data_full, updated_us_data_full])
all_data_updated

,total_pop_city,pct_singlefam_city,pct_multifam_city,pct_mobile_home_and_others_city,pct_renter_city,median_age_city,bachelor_plus_city,median_hhinc_city,median_rent_city,pct_vacant_city,...,days_workplace_closing,days_cancel_large_events,days_cancel_all_events,days_stay_home_requirements,days_income_support,days_mask_mandates,winter_avg_temp,spring_avg_temp,summer_avg_temp,fall_avg_temp
0,2731571.0,36.425472,63.565543,0.008536,47.247805,40.6,36.397963,50910.030196,928.814751,5.608550,...,496.0,365.0,718.0,127.0,802.0,772.0,29.933333,47.216667,71.400000,55.816667
1,1704694.0,14.302294,85.645770,0.051936,63.269193,40.3,31.311946,38843.945475,595.493221,7.592384,...,487.0,471.0,718.0,219.0,779.0,808.0,21.716667,45.950000,70.216667,52.800000
2,1239220.0,72.225615,27.339440,0.434946,28.554441,37.6,33.242481,75274.983353,1011.565108,4.681916,...,602.0,277.0,642.0,0.0,667.0,786.0,22.150000,43.433333,64.250000,46.250000
3,934243.0,69.074661,30.709957,0.214044,34.323287,40.1,37.653332,66494.938497,859.985015,5.613596,...,496.0,365.0,718.0,127.0,802.0,772.0,20.950000,44.700000,68.000000,50.783333
4,932546.0,66.127624,33.139333,0.734428,35.704289,37.7,27.319553,67457.008065,952.789154,6.991107,...,602.0,277.0,642.0,0.0,667.0,786.0,16.983333,41.000000,64.233333,44.266667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,301394.0,43.338182,56.541735,0.120083,62.245054,32.2,21.430885,40640.000000,738.000000,14.993036,...,190.0,158.0,447.0,142.0,644.0,720.0,38.050000,58.383333,77.133333,59.616667
51,302205.0,58.816612,40.814692,0.368696,52.826348,32.9,23.229789,48711.000000,958.000000,12.238814,...,214.0,200.0,369.0,74.0,533.0,735.0,35.033333,55.066667,73.633333,57.200000
52,197756.0,49.665474,49.111416,1.223110,51.911334,32.3,25.739708,60676.000000,985.000000,7.931051,...,78.0,132.0,300.0,0.0,421.0,663.0,32.633333,48.933333,74.750000,55.250000
53,308174.0,46.046772,53.601277,0.351951,56.340876,35.8,19.742603,43896.000000,828.000000,19.678151,...,70.0,345.0,395.0,239.0,421.0,656.0,82.283333,85.466667,86.350000,88.833333
54,280832.0,41.594350,58.078816,0.326834,64.559423,33.8,25.409288,51757.000000,1196.000000,15.746647,...,224.0,193.0,337.0,368.0,421.0,739.0,67.300000,76.100000,85.983333,78.066667

In [134]:
all_data_updated[['city'] + updated_can_vars.columns[updated_can_vars.columns.str.contains("_city")].values.tolist()]

,city,total_pop_city,pct_singlefam_city,pct_multifam_city,pct_mobile_home_and_others_city,pct_renter_city,median_age_city,bachelor_plus_city,median_hhinc_city,median_rent_city,...,pct_commute_public_transit_city,pct_commute_walk_city,pct_commute_bicycle_city,pct_commute_others_city,housing_units_city,average_commute_time_city,land_area_city,population_density_city,housing_density_city,pct_others_city
0,Toronto,2731571.0,36.425472,63.565543,0.008536,47.247805,40.6,36.397963,50910.030196,928.814751,...,37.009164,8.605937,2.746082,1.087882,1112930.0,36.327899,634.43388,4.305525e+03,1.754210e+03,8.818148
1,Montreal,1704694.0,14.302294,85.645770,0.051936,63.269193,40.3,31.311946,38843.945475,595.493221,...,36.549514,8.587567,3.886503,0.891194,779805.0,33.502362,366.11227,4.656206e+03,2.129961e+03,2.425115
2,Calgary,1239220.0,72.225615,27.339440,0.434946,28.554441,37.6,33.242481,75274.983353,1011.565108,...,15.796619,4.950398,1.614420,1.449216,466725.0,29.905601,849.05033,1.459537e+03,5.497024e+02,7.032039
3,Ottawa,934243.0,69.074661,30.709957,0.214044,34.323287,40.1,37.653332,66494.938497,859.985015,...,20.618393,7.377515,2.606570,0.995794,373755.0,30.472917,2892.07371,3.230357e+02,1.292343e+02,2.454028
4,Edmonton,932546.0,66.127624,33.139333,0.734428,35.704289,37.7,27.319553,67457.008065,952.789154,...,14.583088,4.080648,1.195775,1.373800,360825.0,29.334576,700.54067,1.331180e+03,5.150665e+02,7.430617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,Cincinnati,301394.0,43.338182,56.541735,0.120083,62.245054,32.2,21.430885,40640.000000,738.000000,...,7.111457,5.682767,0.357520,5.794753,161555.0,23.248900,NaN,1.495052e+09,8.013869e+08,3.830202
51,Pittsburgh,302205.0,58.816612,40.814692,0.368696,52.826348,32.9,23.229789,48711.000000,958.000000,...,17.637952,10.736940,1.789272,6.516897,157311.0,24.269921,NaN,2.107077e+09,1.096827e+09,3.583660
52,Salt Lake City,197756.0,49.665474,49.111416,1.223110,51.911334,32.3,25.739708,60676.000000,985.000000,...,7.344330,5.145668,2.455081,6.766931,86092.0,19.544851,NaN,6.897484e+08,3.002782e+08,5.678210
53,St Louis,308174.0,46.046772,53.601277,0.351951,56.340876,35.8,19.742603,43896.000000,828.000000,...,8.783453,4.693727,0.777505,5.244894,176729.0,24.384129,NaN,1.927110e+09,1.105143e+09,2.769539
54,Orlando,280832.0,41.594350,58.078816,0.326834,64.559423,33.8,25.409288,51757.000000,1196.000000,...,3.456811,1.769441,0.606665,7.183470,133095.0,26.068035,NaN,9.807428e+08,4.648044e+08,3.267078

In [139]:
all_data_updated = all_data_updated[all_data_updated['city'] != 'Hamilton'].drop(columns = ['land_area_city'])
all_data_updated

,total_pop_city,pct_singlefam_city,pct_multifam_city,pct_mobile_home_and_others_city,pct_renter_city,median_age_city,bachelor_plus_city,median_hhinc_city,median_rent_city,pct_vacant_city,...,days_workplace_closing,days_cancel_large_events,days_cancel_all_events,days_stay_home_requirements,days_income_support,days_mask_mandates,winter_avg_temp,spring_avg_temp,summer_avg_temp,fall_avg_temp
0,2731571.0,36.425472,63.565543,0.008536,47.247805,40.6,36.397963,50910.030196,928.814751,5.608550,...,496.0,365.0,718.0,127.0,802.0,772.0,29.933333,47.216667,71.400000,55.816667
1,1704694.0,14.302294,85.645770,0.051936,63.269193,40.3,31.311946,38843.945475,595.493221,7.592384,...,487.0,471.0,718.0,219.0,779.0,808.0,21.716667,45.950000,70.216667,52.800000
2,1239220.0,72.225615,27.339440,0.434946,28.554441,37.6,33.242481,75274.983353,1011.565108,4.681916,...,602.0,277.0,642.0,0.0,667.0,786.0,22.150000,43.433333,64.250000,46.250000
3,934243.0,69.074661,30.709957,0.214044,34.323287,40.1,37.653332,66494.938497,859.985015,5.613596,...,496.0,365.0,718.0,127.0,802.0,772.0,20.950000,44.700000,68.000000,50.783333
4,932546.0,66.127624,33.139333,0.734428,35.704289,37.7,27.319553,67457.008065,952.789154,6.991107,...,602.0,277.0,642.0,0.0,667.0,786.0,16.983333,41.000000,64.233333,44.266667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,301394.0,43.338182,56.541735,0.120083,62.245054,32.2,21.430885,40640.000000,738.000000,14.993036,...,190.0,158.0,447.0,142.0,644.0,720.0,38.050000,58.383333,77.133333,59.616667
51,302205.0,58.816612,40.814692,0.368696,52.826348,32.9,23.229789,48711.000000,958.000000,12.238814,...,214.0,200.0,369.0,74.0,533.0,735.0,35.033333,55.066667,73.633333,57.200000
52,197756.0,49.665474,49.111416,1.223110,51.911334,32.3,25.739708,60676.000000,985.000000,7.931051,...,78.0,132.0,300.0,0.0,421.0,663.0,32.633333,48.933333,74.750000,55.250000
53,308174.0,46.046772,53.601277,0.351951,56.340876,35.8,19.742603,43896.000000,828.000000,19.678151,...,70.0,345.0,395.0,239.0,421.0,656.0,82.283333,85.466667,86.350000,88.833333
54,280832.0,41.594350,58.078816,0.326834,64.559423,33.8,25.409288,51757.000000,1196.000000,15.746647,...,224.0,193.0,337.0,368.0,421.0,739.0,67.300000,76.100000,85.983333,78.066667

In [148]:
all_data_updated.select_dtypes(include=np.number).columns.tolist()

['total_pop_city',
 'pct_singlefam_city',
 'pct_multifam_city',
 'pct_mobile_home_and_others_city',
 'pct_renter_city',
 'median_age_city',
 'bachelor_plus_city',
 'median_hhinc_city',
 'median_rent_city',
 'pct_vacant_city',
 'pct_nhwhite_city',
 'pct_nhblack_city',
 'pct_hisp_city',
 'pct_nhasian_city',
 'pct_commute_auto_city',
 'pct_commute_public_transit_city',
 'pct_commute_walk_city',
 'pct_commute_bicycle_city',
 'pct_commute_others_city',
 'housing_units_city',
 'average_commute_time_city',
 'population_density_city',
 'housing_density_city',
 'pct_others_city',
 'pct_nhwhite_downtown',
 'pct_nhblack_downtown',
 'pct_hisp_downtown',
 'pct_nhasian_downtown',
 'population_density_downtown',
 'employment_density_downtown',
 'pct_mobile_home_and_others_downtown',
 'housing_density_downtown',
 'pct_others_downtown',
 'total_jobs',
 'total_pop_downtown',
 'pct_singlefam_downtown',
 'pct_multifam_downtown',
 'pct_renter_downtown',
 'median_age_downtown',
 'bachelor_plus_downtown',
 'median_hhinc_downtown',
 'median_rent_downtown',
 'pct_vacant_downtown',
 'pct_commute_auto_downtown',
 'pct_commute_public_transit_downtown',
 'pct_commute_bicycle_downtown',
 'pct_commute_walk_downtown',
 'pct_commute_others_downtown',
 'housing_units_downtown',
 'average_commute_time_downtown',
 'pct_jobs_agriculture_forestry_fishing_hunting',
 'pct_jobs_mining_quarrying_oil_gas',
 'pct_jobs_utilities',
 'pct_jobs_construction',
 'pct_jobs_manufacturing',
 'pct_jobs_wholesale_trade',
 'pct_jobs_retail_trade',
 'pct_jobs_transport_warehouse',
 'pct_jobs_information',
 'pct_jobs_finance_insurance',
 'pct_jobs_real_estate',
 'pct_jobs_professional_science_techical',
 'pct_jobs_management_of_companies_enterprises',
 'pct_jobs_administrative_support_waste',
 'pct_jobs_educational_services',
 'pct_jobs_healthcare_social_assistance',
 'pct_jobs_arts_entertainment_recreation',
 'pct_jobs_accomodation_food_services',
 'pct_jobs_other',
 'pct_jobs_public_administration',
 'employment_entropy',
 'median_year_structure_built',
 'median_no_rooms',
 'days_school_closing',
 'days_workplace_closing',
 'days_cancel_large_events',
 'days_cancel_all_events',
 'days_stay_home_requirements',
 'days_income_support',
 'days_mask_mandates',
 'winter_avg_temp',
 'spring_avg_temp',
 'summer_avg_temp',
 'fall_avg_temp']

In [144]:
all_data_updated[['city', 'average_commute_time_city']].values

array([['Toronto', 36.327899253030445],
       ['Montreal', 33.50236176256854],
       ['Calgary', 29.90560058230353],
       ['Ottawa', 30.472916903489825],
       ['Edmonton', 29.33457558046008],
       ['Mississauga', 34.14238218493395],
       ['Winnipeg', 27.686500109577032],
       ['Vancouver', 30.68761297688136],
       ['Quebec', 26.18400162636256],
       ['Halifax', 27.997085783243897],
       ['London', 25.72360953461975],
       ['New York', 41.5315621142261],
       ['Los Angeles', 31.9540448023944],
       ['Chicago', 35.0614001943215],
       ['Houston', 27.6936827774633],
       ['Phoenix', 26.2177176201844],
       ['Philadelphia', 33.6199138803223],
       ['San Antonio', 24.741490484771],
       ['San Diego', 24.4600376137549],
       ['Dallas', 27.1159953001699],
       ['San Jose', 30.9202396028061],
       ['Austin', 24.5230280742595],
       ['Jacksonville', 25.1591058944449],
       ['Fort Worth', 27.2346067892933],
       ['Columbus', 21.9856491631158],
       ['Indianapolis', 23.6199797755334],
       ['Charlotte', 25.8789672216441],
       ['San Francisco', 33.8436210552706],
       ['Seattle', 27.9099588543123],
       ['Denver', 25.9080576252696],
       ['Washington DC', 30.8032220548047],
       ['Nashville', 25.0077785106075],
       ['Oklahoma City', 21.4137229030474],
       ['El Paso', 23.201616181268],
       ['Boston', 30.8961969730446],
       ['Portland', 26.5218225522731],
       ['Las Vegas', 26.0919847245584],
       ['Detroit', 25.9094202098288],
       ['Memphis', 21.7008933688675],
       ['Louisville', 22.8450562983814],
       ['Baltimore', 31.3768693388583],
       ['Milwaukee', 22.2441163516593],
       ['Albuquerque', 21.8197493942324],
       ['Tucson', 22.5127747865153],
       ['Fresno', 22.2174653729353],
       ['Sacramento', 26.2410060343636],
       ['Kansas City', 22.0073555506734],
       ['Atlanta', 27.1969339362523],
       ['Omaha', 19.1601028054113],
       ['Colorado Springs', 22.7229946324735],
       ['Raleigh', 23.9530017915288],
       ['Miami', 29.2588220675944],
       ['Oakland', 33.4100865946754],
       ['Minneapolis', 23.2210691950057],
       ['Tulsa', 18.6407972741635],
       ['Bakersfield', 23.0317181947756],
       ['Wichita', 18.5713972830759],
       ['Tampa', 24.5688083781489],
       ['New Orleans', 24.1631191376837],
       ['Cleveland', 24.0373188887412],
       ['Honolulu', 23.6638826726343],
       ['Cincinnati', 23.248899562745],
       ['Pittsburgh', 24.2699206909438],
       ['Salt Lake City', 19.5448510097852],
       ['St Louis', 24.3841292756505],
       ['Orlando', 26.0680351784217]], dtype=object)

In [156]:
all_data_updated['average_commute_time_downtown'] = all_data_updated['average_commute_time_downtown'].replace(0, np.nan)

In [157]:
all_data_updated[['city', 'average_commute_time_downtown']].values

array([['Toronto', 30.284428610022964],
       ['Montreal', 28.49498851534767],
       ['Calgary', 25.659458174904945],
       ['Ottawa', 26.555979007872047],
       ['Edmonton', 27.08036396029524],
       ['Mississauga', 34.530600311850314],
       ['Winnipeg', 26.71791839148433],
       ['Vancouver', 28.40674688440052],
       ['Quebec', 24.843260188087772],
       ['Halifax', 23.569444444444443],
       ['London', 24.73105497771174],
       ['New York', 27.254814649894243],
       ['Los Angeles', 32.42431608255624],
       ['Chicago', 23.429020841525755],
       ['Houston', 18.46541367951947],
       ['Phoenix', 19.184080926394248],
       ['Philadelphia', 25.87341011200405],
       ['San Antonio', nan],
       ['San Diego', 24.14705482247313],
       ['Dallas', 22.37532623263032],
       ['San Jose', 32.56122448979592],
       ['Austin', 20.79585798816568],
       ['Jacksonville', nan],
       ['Fort Worth', 23.51926394479586],
       ['Columbus', 19.41210919902694],
       ['Indianapolis', 19.65931863727455],
       ['Charlotte', 19.373117679866144],
       ['San Francisco', 30.39152298850575],
       ['Seattle', 23.06955422067657],
       ['Denver', 25.40251636661211],
       ['Washington DC', 22.18592781625957],
       ['Nashville', nan],
       ['Oklahoma City', nan],
       ['El Paso', 31.020606531881803],
       ['Boston', 22.766240681576143],
       ['Portland', nan],
       ['Las Vegas', 28.18059480554434],
       ['Detroit', 19.618898773743688],
       ['Memphis', 19.725968612064737],
       ['Louisville', nan],
       ['Baltimore', 30.2230247560236],
       ['Milwaukee', 20.392892456232182],
       ['Albuquerque', 18.961626575028635],
       ['Tucson', 19.99045437189767],
       ['Fresno', nan],
       ['Sacramento', 22.048493492601175],
       ['Kansas City', 19.529955008287946],
       ['Atlanta', 19.83333333333333],
       ['Omaha', 16.159348301212002],
       ['Colorado Springs', 20.54813508064516],
       ['Raleigh', 24.33766806259643],
       ['Miami', 23.078682935582272],
       ['Oakland', 33.62931850449598],
       ['Minneapolis', 17.937453462397617],
       ['Tulsa', nan],
       ['Bakersfield', 17.391358641358643],
       ['Wichita', nan],
       ['Tampa', 22.247996113675008],
       ['New Orleans', 16.441747572815533],
       ['Cleveland', 19.55418381344307],
       ['Honolulu', 21.824892202002484],
       ['Cincinnati', 18.805942083490034],
       ['Pittsburgh', 18.71933962264151],
       ['Salt Lake City', 19.90340673036976],
       ['St Louis', 20.075982209043737],
       ['Orlando', 23.03927108348637]], dtype=object)

In [158]:
all_data_updated.to_csv('~/data/downtownrecovery/curated_data/us_can_variables_20230803.csv')